chore(dotfiles): add new tool configs and update symlinks for things
* lazygit,
* alacritty,
* atuin,
* lsd,
* mise,
* bob,
* btop,
* neovide,
* and private config dirs

diff --git a/home/lazygit.yml b/home/lazygit.yml
--- a/home/lazygit.yml
+++ b/home/lazygit.yml
@@ -1,146 +1,221 @@
+git:
+  pagers:
+    - colorArg: always
+      pager: /opt/homebrew/bin/delta --paging=never --dark
 gui:
-  # stuff relating to the UI
-  scrollHeight: 2 # how many lines you scroll by
-  scrollPastBottom: true # enable scrolling past the bottom
-  sidePanelWidth: 0.3333 # number from 0 to 1
-  expandFocusedSidePanel: false
-  mainPanelSplitMode: 'flexible' # one of 'horizontal' | 'flexible' | 'vertical'
+  mainPanelSplitMode: "flexible" # one of 'horizontal' | 'flexible' | 'vertical'
   theme:
     activeBorderColor:
-      - blue
-      - bold
-    inactiveBorderColor:
-      - blue
+      - "#095AA8"
+      - reverse
     optionsTextColor:
       - blue
+    inactiveBorderColor:
+      - "#55575A"
     selectedLineBgColor:
-      - reverse
-    selectedRangeBgColor:
-      - reverse
-  commitLength:
-    show: true
-  mouseEvents: true
-  skipUnstageLineWarning: false
-  skipStashWarning: true
-  showFileTree: false # for rendering changes files in a tree format
-  showRandomTip: false
-  showCommandLog: true
-  commandLogSize: 8
-disableStartupPopups: true
-notARepository: 'skip'
-keybinding:
-  universal:
-    quit: 'q'
-    quit-alt1: '<c-c>' # alternative/alias of quit
-    return: '<esc>' # return to previous menu, will quit if there's nowhere to return
-    quitWithoutChangingDirectory: 'Q'
-    togglePanel: '<tab>' # goto the next panel
-    prevItem: '<up>' # go one line up
-    nextItem: '<down>' # go one line down
-    prevItem-alt: 'k' # go one line up
-    nextItem-alt: 'j' # go one line down
-    prevPage: ',' # go to next page in list
-    nextPage: '.' # go to previous page in list
-    gotoTop: '<' # go to top of list
-    gotoBottom: '>' # go to bottom of list
-    prevBlock: '<left>' # goto the previous block / panel
-    nextBlock: '<right>' # goto the next block / panel
-    prevBlock-alt: 'h' # goto the previous block / panel
-    nextBlock-alt: 'l' # goto the next block / panel
-    nextMatch: 'n'
-    prevMatch: 'N'
-    optionMenu: 'x' # show help menu
-    optionMenu-alt1: '?' # show help menu
-    select: '<space>'
-    goInto: '<enter>'
-    confirm: '<enter>'
-    confirm-alt1: 'y'
-    remove: 'd'
-    new: 'n'
-    edit: 'e'
-    openFile: 'o'
-    scrollUpMain: '<pgup>' # main panel scroll up
-    scrollDownMain: '<pgdown>' # main panel scroll down
-    scrollUpMain-alt1: 'K' # main panel scroll up
-    scrollDownMain-alt1: 'J' # main panel scroll down
-    scrollUpMain-alt2: '<c-u>' # main panel scroll up
-    scrollDownMain-alt2: '<c-d>' # main panel scroll down
-    executeCustomCommand: ':'
-    createRebaseOptionsMenu: 'm'
-    pushFiles: 'P'
-    pullFiles: 'p'
-    refresh: 'R'
-    createPatchOptionsMenu: '<c-p>'
-    nextTab: ']'
-    prevTab: '['
-    nextScreenMode: '+'
-    prevScreenMode: '_'
-    undo: 'z'
-    redo: '<c-z>'
-    filteringMenu: '<c-s>'
-    diffingMenu: 'W'
-    diffingMenu-alt: '<c-e>' # deprecated
-    copyToClipboard: '<c-o>'
-    submitEditorText: '<enter>'
-    appendNewline: '<tab>'
-  status:
-    checkForUpdate: 'u'
-    recentRepos: '<enter>'
-  files:
-    commitChanges: 'c'
-    commitChangesWithoutHook: 'w' # commit changes without pre-commit hook
-    amendLastCommit: 'A'
-    commitChangesWithEditor: 'C'
-    ignoreFile: 'i'
-    refreshFiles: 'r'
-    stashAllChanges: 's'
-    viewStashOptions: 'S'
-    toggleStagedAll: 'a' # stage/unstage all
-    viewResetOptions: 'D'
-    fetch: 'f'
-    toggleTreeView: '`'
-  branches:
-    createPullRequest: 'o'
-    checkoutBranchByName: 'c'
-    forceCheckoutBranch: 'F'
-    rebaseBranch: 'r'
-    mergeIntoCurrentBranch: 'M'
-    viewGitFlowOptions: 'i'
-    fastForward: 'f' # fast-forward this branch from its upstream
-    pushTag: 'P'
-    setUpstream: 'u' # set as upstream of checked-out branch
-    fetchRemote: 'f'
-  commits:
-    squashDown: 's'
-    renameCommit: 'r'
-    renameCommitWithEditor: 'R'
-    viewResetOptions: 'g'
-    markCommitAsFixup: 'f'
-    createFixupCommit: 'F' # create fixup commit for this commit
-    squashAboveCommits: 'S'
-    moveDownCommit: '<c-j>' # move commit down one
-    moveUpCommit: '<c-k>' # move commit up one
-    amendToCommit: 'A'
-    pickCommit: 'p' # pick commit (when mid-rebase)
-    revertCommit: 't'
-    cherryPickCopy: 'c'
-    cherryPickCopyRange: 'C'
-    pasteCommits: 'v'
-    tagCommit: 'T'
-    checkoutCommit: '<enter>'
-    goInto: '<space>'
-    resetCherryPick: '<c-R>'
-    copyCommitMessageToClipboard: '<c-y>'
-  stash:
-    popStash: 'g'
-  commitFiles:
-    checkoutCommitFile: 'c'
-  main:
-    toggleDragSelect: 'v'
-    toggleDragSelect-alt: 'V'
-    toggleSelectHunk: 'a'
-    pickBothHunks: 'b'
-  submodules:
-    init: 'i'
-    update: 'u'
-    bulkMenu: 'b'
+      - "#233385"
+services:
+  "gitlab.com": "gitlab.com:gitlab.com"
+customCommands:
+  - key: "K"
+    context: "files"
+    description: "Generate commit message with Claude Code"
+    # command: "git diff --staged | $(which claude) -p 'Generate a concise git commit message for these staged changes. Output ONLY the raw commit message with no markdown, no code blocks, no backticks, no explanations. Use conventional commit format.' --model haiku --output-format text > /tmp/commit_msg && git commit -e -F /tmp/commit_msg"
+    command: |
+      PROMPT='Generate a concise git commit message for these staged changes. Output ONLY the raw commit message with no markdown, no code blocks, no backticks, no explanations.'
+      if [ -f .git/commit-msg ] && grep -q 'Changelog:' .git/commit-msg; then
+        PROMPT="$PROMPT Use GitLab commit style with a Changelog trailer (e.g. 'Changelog: fixed' or 'Changelog: added'). Valid values: added, fixed, changed, deprecated, removed, security, performance, other."
+      else
+        PROMPT="$PROMPT Use conventional commit format."
+      fi
+      git diff --staged | $(which claude) -p "$PROMPT" --model sonnet --output-format text > /tmp/commit_msg && git commit -e -F /tmp/commit_msg
+    output: terminal
+  - key: "<c-E>"
+    description: Custom git push
+    context: "global"
+    prompts:
+      - type: menu
+        title: "Control Push behaviour"
+        key: "gitOption"
+        options:
+          - name: "Skip CI"
+            description: "Skip CI execution"
+            value: "-o ci.skip"
+          - name: "Create MR"
+            description: "Create MR on push"
+            value: "-o merge_request.create"
+    command: "git push {{.Form.gitOption }}"
+    loadingText: "Pushing changes"
+    output: log
+  - key: "f"
+    command: "git difftool -y {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
+    context: "commitFiles"
+    description: "Compare (difftool) with local copy"
+  - key: "<c-P>"
+    description: "Push to a specific remote repository"
+    context: "global"
+    loadingText: "Pushing ..."
+    prompts:
+      - type: "menuFromCommand"
+        title: "Which remote repository to push to?"
+        command: bash -c "git remote --verbose | grep '/.* (push)'"
+        filter: '(?P<remote>.*)\s+(?P<url>.*) \(push\)'
+        valueFormat: "{{ .remote }}"
+        labelFormat: "{{ .remote | bold | cyan }} {{ .url }}"
+      - type: "menu"
+        title: "How to push?"
+        options:
+          - value: "push"
+          - value: "push --force-with-lease"
+          - value: "push --force"
+    command: "git {{index .PromptResponses 1}} {{index .PromptResponses 0}}"
+  - key: "<c-p>"
+    context: "global"
+    loadingText: "pushing"
+    prompts:
+      - type: "input"
+        title: "which branch do you want to push to?"
+    command: "git push origin {{index .PromptResponses 0}}"
+  - key: "P"
+    command: "git push {{.SelectedRemote.Name}} {{.SelectedLocalCommit.Sha}}:{{.SelectedLocalBranch.Name}}"
+    context: "commits"
+    loadingText: "Pushing commit..."
+    description: "Push a specific commit (and any preceding)"
+    output: log
+  - key: "G"
+    command: "glab mr view -w {{.SelectedLocalBranch.UpstreamBranch}}"
+    context: "localBranches"
+    description: "Go to MR in gitlab"
+    output: log
+  - key: "M"
+    command: "git mergetool {{ .SelectedFile.Name }}"
+    context: "files"
+    loadingText: "opening git mergetool"
+    output: terminal
+  - key: "b"
+    command: "git branch --merged master | grep -v '^[ *]*master$' | xargs -r git branch -d"
+    context: "localBranches"
+    loadingText: "Pruning..."
+    description: "prune local branches that have been merged to master"
+  - key: "G"
+    command: |
+      git fetch -p && for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do git branch -D $branch; done
+    context: "localBranches"
+    description: "Prune local branches no longer on its remote; (G)one."
+    loadingText: "Pruning gone..."
+  - key: "<c-a>"
+    description: "Search the whole history (From a ref and down) for an expression in a file"
+    command: "git checkout {{index .PromptResponses 3}}"
+    context: "commits"
+    prompts:
+      - type: "input"
+        title: "Search word:"
+      - type: "input"
+        title: "File/Subtree:"
+      - type: "input"
+        title: "Ref:"
+        initialValue: "{{index .CheckedOutBranch.Name }}"
+      - type: "menuFromCommand"
+        title: "Commits:"
+        command: "git log --oneline {{index .PromptResponses 2}} -S'{{index .PromptResponses 0}}' --all -- {{index .PromptResponses 1}}"
+        filter: "(?P<commit_id>[0-9a-zA-Z]*) *(?P<commit_msg>.*)"
+        valueFormat: "{{ .commit_id }}"
+        labelFormat: "{{ .commit_id | green | bold }} - {{ .commit_msg | yellow }}"
+  - key: "<c-v>"
+    context: "global"
+    description: "Create new conventional commit"
+    prompts:
+      - type: "menu"
+        key: "Type"
+        title: "Type of change"
+        options:
+          - name: "build"
+            description: "Changes that affect the build system or external dependencies"
+            value: "build"
+          - name: "feat"
+            description: "A new feature"
+            value: "feat"
+          - name: "fix"
+            description: "A bug fix"
+            value: "fix"
+          - name: "chore"
+            description: "Other changes that don't modify src or test files"
+            value: "chore"
+          - name: "ci"
+            description: "Changes to CI configuration files and scripts"
+            value: "ci"
+          - name: "docs"
+            description: "Documentation only changes"
+            value: "docs"
+          - name: "perf"
+            description: "A code change that improves performance"
+            value: "perf"
+          - name: "refactor"
+            description: "A code change that neither fixes a bug nor adds a feature"
+            value: "refactor"
+          - name: "revert"
+            description: "Reverts a previous commit"
+            value: "revert"
+          - name: "style"
+            description: "Changes that do not affect the meaning of the code"
+            value: "style"
+          - name: "test"
+            description: "Adding missing tests or correcting existing tests"
+            value: "test"
+      - type: "input"
+        title: "Scope"
+        key: "Scope"
+        initialValue: ""
+      - type: "menu"
+        key: "Breaking"
+        title: "Breaking change"
+        options:
+          - name: "no"
+            value: nil
+          - name: "yes"
+            value: "!"
+      - type: "input"
+        title: "message"
+        key: "Message"
+        initialValue: ""
+      - type: "confirm"
+        key: "Confirm"
+        title: "Commit"
+        body: "Are you sure you want to commit?"
+    command: "git commit --message '{{.Form.Type}}{{ if .Form.Scope }}({{ .Form.Scope }}){{ end }}{{.Form.Breaking}}: {{.Form.Message}}'"
+    loadingText: "Creating conventional commit..."
+  - key: "K"
+    description: "Disentangle: Squash all changes into a single commit and rebase onto the selected branch"
+    context: localBranches
+    command: |-
+      #!/bin/bash
+
+      # Set the base branch
+      BASE_BRANCH="{{.SelectedLocalBranch.Name}}"
+
+      # Check if the working tree is dirty
+      if [[ -n $(git status --porcelain) ]]; then
+          echo "Error: Working tree is dirty. Please commit or stash your changes before running this script."
+          exit 1
+      fi
+
+      # Get the merge base commit
+      merge_base=$(git merge-base $BASE_BRANCH HEAD)
+
+      # Get the first commit hash, message, and author details
+      first_commit_hash=$(git rev-list --reverse $merge_base..HEAD | head -n 1)
+      first_commit_message=$(git log -1 --format=%B $first_commit_hash)
+
+      # Reset to the merge base
+      git reset $merge_base
+
+      # Stage all changes
+      git add -A
+
+      # Create a new commit with all the changes, using the first commit's message and author
+      GIT_AUTHOR_NAME="$(git log -1 --format='%an' $first_commit_hash)" \
+      GIT_AUTHOR_EMAIL="$(git log -1 --format='%ae' $first_commit_hash)" \
+      git commit -m "$first_commit_message"
+
+      # Rebase onto the base branch
+      git rebase $BASE_BRANCH
